public class Theatre {
        static int theatreId=100 ;
        static String name ;
        static String location ;
        static String city ;
        static int totalScreens ;
       static int totalSeats ;
        static boolean hasDolbySound ;
        static boolean has3D;
        static boolean reclinerSeats ;
        static boolean isOnlineBooking ;
        static boolean isAC ;
        static boolean isFoodAvailable ;
        static String screenType;
        static boolean isWheelchairAccess;
        static boolean isSanitizerDispensers ;
       static  boolean isContactlessEntry ;
        static boolean isFireExitAvailable ;
       static  boolean isSecurityAvailable ;
       static  int staffCount ;
       static  boolean intervalSnacks ;
public static void main(String args[]) {
	System.out.println("Theatre ID: " + theatreId);
	System.out.println("Theatre Name: " + name);
        System.out.println("Location: " + location);
        System.out.println("City: " + city);
        System.out.println("Total Screens: " + totalScreens);
        System.out.println("Total Seats: " + totalSeats);
        System.out.println("Dolby Sound: " + hasDolbySound);
        System.out.println("Supports 3D: " + has3D);
        System.out.println("Recliner Seats: " + reclinerSeats);
        System.out.println("Online Booking: " + isOnlineBooking);
        System.out.println("AC: " + isAC);
        System.out.println("Food Available: " + isFoodAvailable);
        System.out.println("Screen Type: " + screenType);
        System.out.println("Wheelchair Access: " + isWheelchairAccess);
        System.out.println("Sanitizer Dispensers: " + isSanitizerDispensers);
        System.out.println("Contactless Entry: " + isContactlessEntry);
        System.out.println("Fire Exit: " + isFireExitAvailable);
        System.out.println("Security Available: " + isSecurityAvailable);
        System.out.println("Staff Count: " + staffCount);
        System.out.println("Interval Snacks: " + intervalSnacks);
        
   System.out.println("-------------------------------");
	 int theatreId=1001;
        name="PVR Cinemas";
         location="Forum Mall";
          city="Bangalore";
       totalScreens=7;
      totalSeats=1200;
          hasDolbySound=true;
          has3D=true;
         reclinerSeats=true;
         isOnlineBooking=true;
        isAC=true;
        isFoodAvailable=true;
         screenType="IMAX";
         isWheelchairAccess=true;
        isSanitizerDispensers=true;
       isContactlessEntry=true;
        isFireExitAvailable=true;
        isSecurityAvailable=true;
        staffCount=50;
        intervalSnacks=true;
        System.out.println("Theatre Name: " + name);
        System.out.println("Location: " + location);
        System.out.println("City: " + city);
        System.out.println("Total Screens: " + totalScreens);
        System.out.println("Total Seats: " + totalSeats);
        System.out.println("Dolby Sound: " + hasDolbySound);
        System.out.println("Supports 3D: " + has3D);
        System.out.println("Recliner Seats: " + reclinerSeats);
        System.out.println("Online Booking: " + isOnlineBooking);
        System.out.println("AC: " + isAC);
        System.out.println("Food Available: " + isFoodAvailable);
        System.out.println("Screen Type: " + screenType);
        System.out.println("Wheelchair Access: " + isWheelchairAccess);
        System.out.println("Sanitizer Dispensers: " + isSanitizerDispensers);
        System.out.println("Contactless Entry: " + isContactlessEntry);
        System.out.println("Fire Exit: " + isFireExitAvailable);
        System.out.println("Security Available: " + isSecurityAvailable);
        System.out.println("Staff Count: " + staffCount);
        System.out.println("Interval Snacks: " + intervalSnacks);
        System.out.println("Theatre ID: " + theatreId);
    }
}
