public class VideoGames {
        static int gameId  ;
        static String title ;
        static String genre  ;
        static String developer ;
        static String publisher  ;
        static int releaseYear  ;
        static String platform  ;
        static double rating  ;
        static boolean isMultiplayer  ;
        static boolean isOnlineSupport  ;
        static int ageRating  ;
        static String gameEngine ;
        static boolean isOpenWorld ;
        static boolean isControllerSupport  ;
        static String language ;
        static boolean isDownloadableContent ;
        static int numberOfLevels  ;
        static boolean isVRSupported  ;
        static  boolean isAchievements  ;
        static String soundtrack ;
        static boolean isInGamePurchases  ;
public static void main(String args[]) {
	 System.out.println("Game Title: " + title);
        System.out.println("Genre: " + genre);
        System.out.println("Developer: " + developer);
        System.out.println("Publisher: " + publisher);
        System.out.println("Release Year: " + releaseYear);
        System.out.println("Platform: " + platform);
        System.out.println("Rating: " + rating);
        System.out.println("Multiplayer: " + isMultiplayer);
        System.out.println("Online Support: " + isOnlineSupport);
        System.out.println("Age Rating: " + ageRating);
        System.out.println("Game Engine: " + gameEngine);
        System.out.println("Open World: " + isOpenWorld);
        System.out.println("Controller Support: " + isControllerSupport);
        System.out.println("Language: " + language);
        System.out.println("Downloadable Content: " + isDownloadableContent);
        System.out.println("Number of Levels: " + numberOfLevels);
        System.out.println("VR Supported: " + isVRSupported);
        System.out.println("Achievements: " + isAchievements);
        System.out.println("Soundtrack: " + soundtrack);
        System.out.println("In-Game Purchases: " + isInGamePurchases);
	
 gameId = 1301;
  title = "The Legend of Zelda";
     genre = "Action-Adventure";
         developer = "Nintendo";
         publisher = "Nintendo";
         releaseYear = 2017;
       platform = "Nintendo Switch";
      rating = 9.5;
      isMultiplayer = false;
       isOnlineSupport = false;
       ageRating = 12;
        gameEngine = "Custom Engine";
        isOpenWorld = true;
          isControllerSupport = true;
         language = "English";
         isDownloadableContent = true;
        numberOfLevels = 120;
         isVRSupported = false;
         isAchievements = true;
        soundtrack = "Epic Orchestral";
          isInGamePurchases = false;
        System.out.println("Game Title: " + title);
        System.out.println("Genre: " + genre);
        System.out.println("Developer: " + developer);
        System.out.println("Publisher: " + publisher);
        System.out.println("Release Year: " + releaseYear);
        System.out.println("Platform: " + platform);
        System.out.println("Rating: " + rating);
        System.out.println("Multiplayer: " + isMultiplayer);
        System.out.println("Online Support: " + isOnlineSupport);
        System.out.println("Age Rating: " + ageRating);
        System.out.println("Game Engine: " + gameEngine);
        System.out.println("Open World: " + isOpenWorld);
        System.out.println("Controller Support: " + isControllerSupport);
        System.out.println("Language: " + language);
        System.out.println("Downloadable Content: " + isDownloadableContent);
        System.out.println("Number of Levels: " + numberOfLevels);
        System.out.println("VR Supported: " + isVRSupported);
        System.out.println("Achievements: " + isAchievements);
        System.out.println("Soundtrack: " + soundtrack);
        System.out.println("In-Game Purchases: " + isInGamePurchases);
    }
}
